# Generated by Django 5.0.2 on 2024-04-27 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_que', models.CharField(max_length=300)),
                ('candidates', models.ManyToManyField(related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
